version: '3.9'
services:
  postgresql:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tcg
    volumes:
      - db-data:/tcg
    ports:
      - 5432
  java:
    image: "domain314/tcgv2"
    ports:
      - "10002:10002"
    depends_on:
      - postgresql
    environment:
      - IS_DOCKER=true

volumes:
  db-data:
