version: '3.9'
services:
  postgresql:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tcg
    volumes:
      - db-data:/tcg
    ports:
      - 5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5

  java:
    image: "domain314/tcgv2"
    ports:
      - "10002:10002"
    depends_on:
      postgresql:
        condition: service_healthy

    environment:
      - IS_DOCKER=true

volumes:
  db-data:
